# -*- coding: utf-8 -*-
"""Part II data: the 16 core present-tense verbs, each taught the same way.

Each verb is a dict consumed by three renderers:
  - the teaching book  (meaning, when-used, trick, conjugation, examples)
  - the practice book  (fill / translate / conversation drills)
  - the answer book    (every exercise with its worked answer)

Sentences are personalized to Celeste's life: Florida beach life,
paddleboarding, dogs, gardening, the gym, coffee, cooking, work, texting,
and her Cuban boyfriend.
"""

PRONOUNS = ["yo", "tú", "él / ella / usted", "nosotros", "vosotros",
            "ellos / ellas / ustedes"]

def _conj(*forms):
    return list(zip(PRONOUNS, forms))

VERBS = [
{
  "inf": "Ser",
  "meaning": "to be (permanent — who/what something is)",
  "gloss": "identity, origin, description, time",
  "when": [
    "Who or what someone is: <span class='es'>Soy Celeste.</span> — I am Celeste.",
    "Where someone is <em>from</em>: <span class='es'>Él es de Cuba.</span> — He is from Cuba.",
    "Permanent traits: <span class='es'>El café es fuerte.</span> — The coffee is strong.",
    "Telling time & dates: <span class='es'>Son las ocho.</span> — It's eight o'clock.",
  ],
  "trick": "SER = the essence. If it's basically <em>always</em> true — your name, "
           "where you're from, what something is made of — use <strong>ser</strong>. "
           "Think \"SER = the Story of who you are.\"",
  "pattern": "Completely irregular — memorize it as a little song: soy, eres, es… "
             "somos, sois, son.",
  "conj": _conj("soy", "eres", "es", "somos", "sois", "son"),
  "examples": [
    ("Soy de Florida, pero mi novio es de La Habana.", "I'm from Florida, but my boyfriend is from Havana."),
    ("Él es cubano y muy simpático.", "He is Cuban and very friendly."),
    ("Somos una pareja feliz.", "We are a happy couple."),
    ("El mar es azul hoy.", "The sea is blue today."),
    ("Mi perro es grande y cariñoso.", "My dog is big and affectionate."),
    ("Las plantas del jardín son tropicales.", "The garden plants are tropical."),
    ("El café cubano es muy dulce.", "Cuban coffee is very sweet."),
    ("¿Eres tú la profesora de yoga?", "Are you the yoga teacher?"),
    ("Son las seis de la mañana y voy a la playa.", "It's six in the morning and I'm going to the beach."),
    ("El gimnasio es nuevo.", "The gym is new."),
    ("Mi trabajo es interesante pero difícil.", "My job is interesting but hard."),
    ("Ustedes son muy amables.", "You all are very kind."),
    ("La paella es un plato español.", "Paella is a Spanish dish."),
    ("Hoy es lunes.", "Today is Monday."),
    ("Nosotros somos vecinos.", "We are neighbors."),
  ],
  "fill": [
    ("Yo ___ de los Estados Unidos.", "soy"),
    ("Mi novio ___ cubano.", "es"),
    ("Nosotros ___ amigos.", "somos"),
    ("¿Tú ___ profesora?", "eres"),
    ("Ellos ___ de Colombia.", "son"),
    ("El agua del mar ___ fría hoy.", "es"),
    ("Ustedes ___ muy simpáticos.", "son"),
    ("___ las tres de la tarde.", "Son"),
  ],
  "translate": [
    ("I am from Florida.", "Soy de Florida."),
    ("He is my boyfriend.", "Él es mi novio."),
    ("We are happy.", "Somos felices."),
    ("The dogs are big.", "Los perros son grandes."),
    ("You (informal) are very kind.", "Eres muy amable."),
    ("It's nine o'clock.", "Son las nueve."),
  ],
  "speak": [
    "Say three permanent facts about yourself using <span class='es'>soy</span>.",
    "Describe your boyfriend in two sentences with <span class='es'>es</span>.",
    "Tell the time out loud right now using <span class='es'>son las…</span>.",
  ],
},
{
  "inf": "Estar",
  "meaning": "to be (temporary — states, feelings, location)",
  "gloss": "feelings, conditions, where things are",
  "when": [
    "How you feel right now: <span class='es'>Estoy cansada.</span> — I'm tired.",
    "Where something is located: <span class='es'>El perro está en el jardín.</span> — The dog is in the garden.",
    "Temporary conditions: <span class='es'>El café está caliente.</span> — The coffee is hot.",
    "The -ing form (with gerund): <span class='es'>Estoy cocinando.</span> — I'm cooking.",
  ],
  "trick": "ESTAR = your STATE and your STATION (location). Feelings change and "
           "places you stand in change — both use <strong>estar</strong>. "
           "\"How you ARE and whERE you are.\"",
  "pattern": "Irregular <em>yo</em> (estoy) and accent marks on estás, está, están. "
             "Nosotros is regular: estamos.",
  "conj": _conj("estoy", "estás", "está", "estamos", "estáis", "están"),
  "examples": [
    ("Estoy en la playa con mi tabla de paddle.", "I'm at the beach with my paddleboard."),
    ("Mi novio está cansado después del gimnasio.", "My boyfriend is tired after the gym."),
    ("El café está muy caliente.", "The coffee is very hot."),
    ("¿Dónde están las llaves?", "Where are the keys?"),
    ("Estamos contentos hoy.", "We are happy today."),
    ("Las plantas están secas; necesitan agua.", "The plants are dry; they need water."),
    ("Estoy cocinando arroz con pollo.", "I'm cooking chicken and rice."),
    ("El perro está durmiendo en el sofá.", "The dog is sleeping on the couch."),
    ("Estás muy guapo hoy.", "You look very handsome today."),
    ("La tienda está cerca de la casa.", "The store is near the house."),
    ("Estoy nerviosa por mi clase de español.", "I'm nervous about my Spanish class."),
    ("¿Cómo estás, mi amor?", "How are you, my love?"),
    ("Estamos en el gimnasio a las siete.", "We're at the gym at seven."),
    ("El mar está tranquilo esta mañana.", "The sea is calm this morning."),
    ("Los platos están en la cocina.", "The dishes are in the kitchen."),
  ],
  "fill": [
    ("Yo ___ muy cansada hoy.", "estoy"),
    ("El café ___ frío.", "está"),
    ("Nosotros ___ en la playa.", "estamos"),
    ("¿Tú ___ bien?", "estás"),
    ("Los perros ___ en el jardín.", "están"),
    ("Ella ___ cocinando.", "está"),
    ("¿Dónde ___ ustedes?", "están"),
    ("Yo ___ nerviosa.", "estoy"),
  ],
  "translate": [
    ("I'm tired.", "Estoy cansada."),
    ("The coffee is cold.", "El café está frío."),
    ("Where are the dogs?", "¿Dónde están los perros?"),
    ("We are at the beach.", "Estamos en la playa."),
    ("How are you? (informal)", "¿Cómo estás?"),
    ("She is cooking.", "Ella está cocinando."),
  ],
  "speak": [
    "Say how you feel right now with <span class='es'>estoy…</span>",
    "Say where three things in your house are using <span class='es'>está / están</span>.",
    "Ask your boyfriend how he is: <span class='es'>¿Cómo estás?</span>",
  ],
},
{
  "inf": "Ir",
  "meaning": "to go",
  "gloss": "movement + the easy future (ir a + verb)",
  "when": [
    "Going somewhere: <span class='es'>Voy a la playa.</span> — I'm going to the beach.",
    "The near future — <em>ir a + infinitive</em>: <span class='es'>Voy a nadar.</span> — I'm going to swim.",
    "Suggestions: <span class='es'>¡Vamos!</span> — Let's go!",
  ],
  "trick": "IR is tiny and totally irregular — it borrows a 'v': voy, vas, va, "
           "vamos, vais, van. Chant \"VOY, VAS, VA\" like a beach cheer. And "
           "<span class='es'>voy a + verb</span> is your shortcut to the future.",
  "pattern": "Fully irregular. Note <span class='es'>vamos</span> also means \"let's go.\"",
  "conj": _conj("voy", "vas", "va", "vamos", "vais", "van"),
  "examples": [
    ("Voy a la playa todos los días.", "I go to the beach every day."),
    ("Vamos a hacer paddleboard esta tarde.", "We're going to paddleboard this afternoon."),
    ("Mi novio va al gimnasio por la mañana.", "My boyfriend goes to the gym in the morning."),
    ("¿Vas a la tienda?", "Are you going to the store?"),
    ("Voy a cocinar esta noche.", "I'm going to cook tonight."),
    ("Los perros van al parque con nosotros.", "The dogs go to the park with us."),
    ("Vamos a la playa a ver el atardecer.", "Let's go to the beach to watch the sunset."),
    ("Ella va a estudiar español conmigo.", "She's going to study Spanish with me."),
    ("¿Adónde van ustedes?", "Where are you all going?"),
    ("Voy a comprar café cubano.", "I'm going to buy Cuban coffee."),
    ("Vamos al mercado los sábados.", "We go to the market on Saturdays."),
    ("Mañana voy a regar las plantas.", "Tomorrow I'm going to water the plants."),
    ("¿Vamos a bailar salsa esta noche?", "Shall we go dancing salsa tonight?"),
    ("Él va a la casa de su mamá.", "He's going to his mom's house."),
  ],
  "fill": [
    ("Yo ___ a la playa.", "voy"),
    ("Nosotros ___ al gimnasio.", "vamos"),
    ("¿Tú ___ a la tienda?", "vas"),
    ("Ella ___ a cocinar.", "va"),
    ("Ellos ___ al parque.", "van"),
    ("Yo ___ a estudiar español.", "voy"),
    ("¿Adónde ___ ustedes?", "van"),
    ("¡___ a la playa!", "Vamos"),
  ],
  "translate": [
    ("I'm going to the beach.", "Voy a la playa."),
    ("We're going to swim.", "Vamos a nadar."),
    ("Are you going to the gym?", "¿Vas al gimnasio?"),
    ("Let's go!", "¡Vamos!"),
    ("She's going to study.", "Ella va a estudiar."),
    ("I'm going to cook tonight.", "Voy a cocinar esta noche."),
  ],
  "speak": [
    "Say three places you go this week with <span class='es'>voy a…</span>",
    "Make three future plans with <span class='es'>voy a + verb</span>.",
    "Invite someone somewhere: <span class='es'>¿Vamos a…?</span>",
  ],
},
{
  "inf": "Tener",
  "meaning": "to have",
  "gloss": "possession + many everyday expressions",
  "when": [
    "Possession: <span class='es'>Tengo dos perros.</span> — I have two dogs.",
    "Age: <span class='es'>Tengo treinta años.</span> — I'm thirty (lit. I have 30 years).",
    "Feelings/states — <em>tener</em> idioms: <span class='es'>Tengo hambre / sed / frío / calor / sueño / miedo / prisa.</span>",
    "Obligation — <em>tener que + verb</em>: <span class='es'>Tengo que trabajar.</span> — I have to work.",
  ],
  "trick": "TENER stem changes e→ie (tiene) but the <em>yo</em> form grows a 'g': "
           "<strong>tengo</strong>. Remember \"I've GOT it\" → ten<strong>go</strong>. "
           "And in Spanish you don't <em>are</em> hungry, you <em>have</em> hunger.",
  "pattern": "Irregular yo (tengo) + stem change e→ie in tú/él/ellos.",
  "conj": _conj("tengo", "tienes", "tiene", "tenemos", "tenéis", "tienen"),
  "examples": [
    ("Tengo dos perros y un gato.", "I have two dogs and a cat."),
    ("Mi novio tiene una moto.", "My boyfriend has a motorcycle."),
    ("Tenemos una casa cerca de la playa.", "We have a house near the beach."),
    ("Tengo hambre; vamos a comer.", "I'm hungry; let's eat."),
    ("¿Tienes sed? Hay agua fría.", "Are you thirsty? There's cold water."),
    ("Tengo que ir al gimnasio hoy.", "I have to go to the gym today."),
    ("Él tiene muchos amigos cubanos.", "He has many Cuban friends."),
    ("Tengo treinta y dos años.", "I'm thirty-two years old."),
    ("Tenemos prisa; el café va a cerrar.", "We're in a hurry; the café is going to close."),
    ("Las plantas tienen sed también.", "The plants are thirsty too."),
    ("Tengo ganas de ir a la playa.", "I feel like going to the beach."),
    ("¿Cuántos años tiene tu perro?", "How old is your dog?"),
    ("Tengo frío en el aire acondicionado.", "I'm cold in the air conditioning."),
    ("Ustedes tienen razón.", "You all are right."),
  ],
  "fill": [
    ("Yo ___ dos perros.", "tengo"),
    ("Mi novio ___ una moto.", "tiene"),
    ("Nosotros ___ una casa.", "tenemos"),
    ("¿Tú ___ hambre?", "tienes"),
    ("Ellos ___ muchos amigos.", "tienen"),
    ("Yo ___ que trabajar hoy.", "tengo"),
    ("¿Cuántos años ___ tú?", "tienes"),
    ("Las plantas ___ sed.", "tienen"),
  ],
  "translate": [
    ("I have two dogs.", "Tengo dos perros."),
    ("He has a motorcycle.", "Él tiene una moto."),
    ("I'm hungry.", "Tengo hambre."),
    ("We have to work.", "Tenemos que trabajar."),
    ("Are you thirsty?", "¿Tienes sed?"),
    ("I'm thirty years old.", "Tengo treinta años."),
  ],
  "speak": [
    "List what you have at home with <span class='es'>tengo…</span>",
    "Say three things you <em>have to</em> do today with <span class='es'>tengo que…</span>",
    "Use three <span class='es'>tener</span> feelings: hambre, sed, sueño…",
  ],
},
{
  "inf": "Hacer",
  "meaning": "to do / to make",
  "gloss": "activities + weather",
  "when": [
    "Doing an activity: <span class='es'>Hago ejercicio.</span> — I exercise.",
    "Making something: <span class='es'>Hago café.</span> — I make coffee.",
    "Weather: <span class='es'>Hace calor / sol / frío / viento.</span> — It's hot / sunny / cold / windy.",
    "Asking what someone does: <span class='es'>¿Qué haces?</span> — What are you doing?",
  ],
  "trick": "HACER's <em>yo</em> form swaps c→g: <strong>hago</strong>. And for weather, "
           "Spanish says it \"MAKES\" heat: <span class='es'>hace calor</span>. "
           "Picture the sun literally making the heat.",
  "pattern": "Irregular yo (hago); everything else regular -er.",
  "conj": _conj("hago", "haces", "hace", "hacemos", "hacéis", "hacen"),
  "examples": [
    ("Hago ejercicio en el gimnasio todos los días.", "I exercise at the gym every day."),
    ("Hoy hace mucho calor en Florida.", "Today it's very hot in Florida."),
    ("Mi novio hace café cubano por la mañana.", "My boyfriend makes Cuban coffee in the morning."),
    ("¿Qué haces este fin de semana?", "What are you doing this weekend?"),
    ("Hacemos paddleboard cuando hace buen tiempo.", "We paddleboard when the weather is nice."),
    ("Hace sol, vamos a la playa.", "It's sunny, let's go to the beach."),
    ("Hago la cena para los dos.", "I make dinner for the two of us."),
    ("Los niños hacen mucho ruido.", "The kids make a lot of noise."),
    ("¿Haces yoga por la mañana?", "Do you do yoga in the morning?"),
    ("Hace viento hoy, no hay paddleboard.", "It's windy today, no paddleboarding."),
    ("Hacemos una fiesta el sábado.", "We're throwing a party on Saturday."),
    ("Hago una lista para el supermercado.", "I make a list for the supermarket."),
    ("¿Qué hace tu perro todo el día?", "What does your dog do all day?"),
    ("Hace fresco por la noche.", "It's cool at night."),
  ],
  "fill": [
    ("Yo ___ ejercicio.", "hago"),
    ("Hoy ___ calor.", "hace"),
    ("Nosotros ___ paddleboard.", "hacemos"),
    ("¿Tú ___ yoga?", "haces"),
    ("Ellos ___ mucho ruido.", "hacen"),
    ("Mi novio ___ café.", "hace"),
    ("¿Qué ___ tú hoy?", "haces"),
    ("___ viento en la playa.", "Hace"),
  ],
  "translate": [
    ("I make coffee.", "Hago café."),
    ("It's hot today.", "Hoy hace calor."),
    ("What are you doing?", "¿Qué haces?"),
    ("We exercise every day.", "Hacemos ejercicio todos los días."),
    ("It's sunny.", "Hace sol."),
    ("She makes dinner.", "Ella hace la cena."),
  ],
  "speak": [
    "Describe today's weather with <span class='es'>hace…</span>",
    "Say three things you do in a normal day with <span class='es'>hago…</span>",
    "Ask a friend what they're doing this weekend.",
  ],
},
{
  "inf": "Ver",
  "meaning": "to see / to watch",
  "gloss": "seeing, watching TV/videos",
  "when": [
    "Seeing: <span class='es'>Veo el mar.</span> — I see the sea.",
    "Watching: <span class='es'>Veo videos en español.</span> — I watch videos in Spanish.",
    "Meeting up: <span class='es'>Nos vemos mañana.</span> — See you tomorrow.",
  ],
  "trick": "VER keeps an extra 'e' in the yo form: <strong>veo</strong> (not 'vo'). "
           "Tiny word, tiny irregularity. \"I VE-O what you did there.\"",
  "pattern": "Only oddity is yo = veo and vosotros = veis (no accent).",
  "conj": _conj("veo", "ves", "ve", "vemos", "veis", "ven"),
  "examples": [
    ("Veo el atardecer desde la playa.", "I watch the sunset from the beach."),
    ("Veo videos en español en YouTube.", "I watch videos in Spanish on YouTube."),
    ("Mi novio ve fútbol los domingos.", "My boyfriend watches soccer on Sundays."),
    ("¿Ves el barco allá?", "Do you see the boat over there?"),
    ("Vemos una película cubana esta noche.", "We're watching a Cuban movie tonight."),
    ("No veo bien sin mis gafas de sol.", "I can't see well without my sunglasses."),
    ("Los perros ven un gato en el jardín.", "The dogs see a cat in the garden."),
    ("Nos vemos mañana en el café.", "See you tomorrow at the café."),
    ("Veo a mi novio todos los días.", "I see my boyfriend every day."),
    ("¿Ustedes ven las estrellas por la noche?", "Do you all see the stars at night?"),
    ("Veo delfines cuando hago paddleboard.", "I see dolphins when I paddleboard."),
    ("Ella ve una serie en español para practicar.", "She watches a series in Spanish to practice."),
  ],
  "fill": [
    ("Yo ___ el mar.", "veo"),
    ("Nosotros ___ una película.", "vemos"),
    ("¿Tú ___ el barco?", "ves"),
    ("Él ___ fútbol.", "ve"),
    ("Ellos ___ un gato.", "ven"),
    ("Yo ___ videos en español.", "veo"),
    ("¿Ustedes ___ las estrellas?", "ven"),
    ("Nos ___ mañana.", "vemos"),
  ],
  "translate": [
    ("I watch videos in Spanish.", "Veo videos en español."),
    ("Do you see the sea?", "¿Ves el mar?"),
    ("We watch a movie.", "Vemos una película."),
    ("See you tomorrow.", "Nos vemos mañana."),
    ("He watches soccer.", "Él ve fútbol."),
    ("I see dolphins.", "Veo delfines."),
  ],
  "speak": [
    "Say three things you can see right now with <span class='es'>veo…</span>",
    "Say what you watch to practice Spanish.",
    "Close a chat with <span class='es'>nos vemos…</span>",
  ],
},
{
  "inf": "Venir",
  "meaning": "to come",
  "gloss": "coming toward the speaker",
  "when": [
    "Coming here: <span class='es'>Ven a la playa.</span> — Come to the beach.",
    "Where someone's coming from: <span class='es'>Vengo del gimnasio.</span> — I'm coming from the gym.",
    "Invitations: <span class='es'>¿Vienes conmigo?</span> — Are you coming with me?",
  ],
  "trick": "VENIR is TENER's twin: same 'g' in yo (<strong>vengo</strong>) and same "
           "e→ie stem change (viene). Learn one, get the other free.",
  "pattern": "Irregular yo (vengo) + stem change e→ie, exactly like tener.",
  "conj": _conj("vengo", "vienes", "viene", "venimos", "venís", "vienen"),
  "examples": [
    ("Vengo del gimnasio ahora mismo.", "I'm coming from the gym right now."),
    ("¿Vienes conmigo a la playa?", "Are you coming with me to the beach?"),
    ("Mi novio viene a mi casa esta noche.", "My boyfriend is coming to my house tonight."),
    ("Venimos del mercado con mucha comida.", "We're coming from the market with lots of food."),
    ("Mis amigos vienen de Cuba el mes que viene.", "My friends are coming from Cuba next month."),
    ("¿A qué hora vienes?", "What time are you coming?"),
    ("El perro viene cuando lo llamo.", "The dog comes when I call it."),
    ("Vengo a la clase de español los lunes.", "I come to Spanish class on Mondays."),
    ("Ellos vienen a la fiesta el sábado.", "They're coming to the party on Saturday."),
    ("Ven aquí, mi amor.", "Come here, my love."),
    ("Venimos temprano para ver el atardecer.", "We come early to watch the sunset."),
    ("La lluvia viene del mar.", "The rain comes from the sea."),
  ],
  "fill": [
    ("Yo ___ del gimnasio.", "vengo"),
    ("¿Tú ___ conmigo?", "vienes"),
    ("Nosotros ___ del mercado.", "venimos"),
    ("Él ___ a mi casa.", "viene"),
    ("Ellos ___ a la fiesta.", "vienen"),
    ("Yo ___ a clase los lunes.", "vengo"),
    ("¿A qué hora ___ ustedes?", "vienen"),
    ("El perro ___ cuando lo llamo.", "viene"),
  ],
  "translate": [
    ("I'm coming from the gym.", "Vengo del gimnasio."),
    ("Are you coming with me?", "¿Vienes conmigo?"),
    ("He comes to my house.", "Él viene a mi casa."),
    ("We come early.", "Venimos temprano."),
    ("Come here.", "Ven aquí."),
    ("They're coming to the party.", "Ellos vienen a la fiesta."),
  ],
  "speak": [
    "Say where you're coming from with <span class='es'>vengo de…</span>",
    "Invite someone: <span class='es'>¿Vienes a…?</span>",
    "Tell your dog to come: <span class='es'>¡Ven!</span>",
  ],
},
{
  "inf": "Decir",
  "meaning": "to say / to tell",
  "gloss": "speech, reporting what people say",
  "when": [
    "Reporting speech: <span class='es'>Digo la verdad.</span> — I tell the truth.",
    "What people say: <span class='es'>Mi novio dice \"dale\".</span> — My boyfriend says \"dale.\"",
    "Telling someone something: <span class='es'>Te digo un secreto.</span> — I'll tell you a secret.",
  ],
  "trick": "DECIR gets the 'g' yo (<strong>digo</strong>) <em>and</em> a stem change "
           "e→i (dice). Think \"I DIG-O telling stories.\"",
  "pattern": "Irregular yo (digo) + stem change e→i.",
  "conj": _conj("digo", "dices", "dice", "decimos", "decís", "dicen"),
  "examples": [
    ("Siempre digo la verdad.", "I always tell the truth."),
    ("Mi novio dice \"dale\" para todo.", "My boyfriend says \"dale\" for everything."),
    ("¿Qué dices? No te oigo.", "What are you saying? I can't hear you."),
    ("Los cubanos dicen \"asere\" a los amigos.", "Cubans say \"asere\" to friends."),
    ("Te digo un secreto.", "I'll tell you a secret."),
    ("Decimos \"buenos días\" por la mañana.", "We say \"good morning\" in the morning."),
    ("La profesora dice que estudio bien.", "The teacher says I study well."),
    ("Ellos dicen que hace buen tiempo mañana.", "They say the weather is nice tomorrow."),
    ("Mi mamá siempre dice que coma más.", "My mom always says to eat more."),
    ("¿Cómo se dice 'beach' en español?", "How do you say 'beach' in Spanish?"),
    ("Dice que viene a la fiesta.", "He says he's coming to the party."),
    ("Nunca digo mentiras.", "I never tell lies."),
  ],
  "fill": [
    ("Yo siempre ___ la verdad.", "digo"),
    ("Mi novio ___ \"dale\".", "dice"),
    ("¿Qué ___ tú?", "dices"),
    ("Nosotros ___ \"buenos días\".", "decimos"),
    ("Ellos ___ que hace calor.", "dicen"),
    ("Yo te ___ un secreto.", "digo"),
    ("¿Cómo se ___ 'dog'?", "dice"),
    ("Ustedes ___ la verdad.", "dicen"),
  ],
  "translate": [
    ("I always tell the truth.", "Siempre digo la verdad."),
    ("What do you say?", "¿Qué dices?"),
    ("He says he's coming.", "Dice que viene."),
    ("We say good morning.", "Decimos buenos días."),
    ("How do you say 'beach'?", "¿Cómo se dice 'beach'?"),
    ("They say it's hot.", "Dicen que hace calor."),
  ],
  "speak": [
    "Tell a friend a fact starting with <span class='es'>digo que…</span>",
    "Ask how to say three English words: <span class='es'>¿Cómo se dice…?</span>",
    "Report what your boyfriend always says.",
  ],
},
{
  "inf": "Dar",
  "meaning": "to give",
  "gloss": "giving + friendly idioms",
  "when": [
    "Giving: <span class='es'>Doy comida al perro.</span> — I give food to the dog.",
    "Going for a walk: <span class='es'>Doy un paseo por la playa.</span> — I take a walk on the beach.",
    "\"Dale\" — the ultra-Cuban \"okay / go for it\": <span class='es'>Dale, vamos.</span>",
  ],
  "trick": "DAR looks like a mini-ir: <strong>doy</strong>, das, da, damos, dais, dan. "
           "Same '-oy' ending as voy and soy. Learn the trio: soy / voy / doy.",
  "pattern": "Irregular yo (doy); rest regular -ar.",
  "conj": _conj("doy", "das", "da", "damos", "dais", "dan"),
  "examples": [
    ("Doy de comer a los perros a las siete.", "I feed the dogs at seven."),
    ("Damos un paseo por la playa cada tarde.", "We take a walk on the beach every afternoon."),
    ("Mi novio me da un beso.", "My boyfriend gives me a kiss."),
    ("¿Me das un poco de café?", "Will you give me some coffee?"),
    ("Doy las gracias por la comida.", "I give thanks for the food."),
    ("El sol da mucha luz por la mañana.", "The sun gives a lot of light in the morning."),
    ("Damos agua a las plantas cada día.", "We give water to the plants every day."),
    ("Ella da clases de yoga en la playa.", "She gives yoga classes on the beach."),
    ("Dale, vamos al mercado.", "Come on, let's go to the market."),
    ("Te doy mi número.", "I'll give you my number."),
    ("Los árboles dan sombra.", "The trees give shade."),
    ("¿Le das de comer al perro?", "Do you feed the dog?"),
  ],
  "fill": [
    ("Yo ___ de comer al perro.", "doy"),
    ("Nosotros ___ un paseo.", "damos"),
    ("¿Me ___ un café?", "das"),
    ("El sol ___ mucha luz.", "da"),
    ("Ellos ___ las gracias.", "dan"),
    ("Yo te ___ mi número.", "doy"),
    ("Ella ___ clases de yoga.", "da"),
    ("¿Ustedes ___ agua a las plantas?", "dan"),
  ],
  "translate": [
    ("I feed the dogs.", "Doy de comer a los perros."),
    ("We take a walk.", "Damos un paseo."),
    ("Will you give me a coffee?", "¿Me das un café?"),
    ("He gives me a kiss.", "Él me da un beso."),
    ("I give thanks.", "Doy las gracias."),
    ("She gives yoga classes.", "Ella da clases de yoga."),
  ],
  "speak": [
    "Say who you give things to with <span class='es'>doy…</span>",
    "Suggest a plan and reply <span class='es'>¡Dale!</span>",
    "Describe your daily walk with <span class='es'>doy un paseo…</span>",
  ],
},
{
  "inf": "Poner",
  "meaning": "to put / to set / to turn on",
  "gloss": "placing things, playing music, setting the table",
  "when": [
    "Putting things somewhere: <span class='es'>Pongo las llaves en la mesa.</span>",
    "Playing music: <span class='es'>Pongo música.</span> — I put on music.",
    "Getting dressed (ponerse): <span class='es'>Me pongo el traje de baño.</span>",
  ],
  "trick": "PONER's yo grows the 'g' again: <strong>pongo</strong>. Same family as "
           "tengo / vengo / digo. When in doubt on a yo form, try adding 'g'.",
  "pattern": "Irregular yo (pongo); rest regular -er.",
  "conj": _conj("pongo", "pones", "pone", "ponemos", "ponéis", "ponen"),
  "examples": [
    ("Pongo música cuando cocino.", "I put on music when I cook."),
    ("Pongo las llaves en la mesa.", "I put the keys on the table."),
    ("Mi novio pone salsa cubana en el carro.", "My boyfriend plays Cuban salsa in the car."),
    ("Me pongo el traje de baño para la playa.", "I put on my swimsuit for the beach."),
    ("Ponemos la mesa antes de cenar.", "We set the table before dinner."),
    ("¿Pones el aire acondicionado, por favor?", "Will you turn on the A/C, please?"),
    ("Pongo crema solar antes de nadar.", "I put on sunscreen before swimming."),
    ("Ella pone las plantas al sol.", "She puts the plants in the sun."),
    ("Ellos ponen la mesa para la fiesta.", "They set the table for the party."),
    ("Pongo el café en la cafetera.", "I put the coffee in the coffee maker."),
    ("¿Dónde pongo la tabla de paddle?", "Where do I put the paddleboard?"),
    ("Me pongo nerviosa antes de hablar.", "I get nervous before speaking."),
  ],
  "fill": [
    ("Yo ___ música.", "pongo"),
    ("Nosotros ___ la mesa.", "ponemos"),
    ("¿Tú ___ el aire?", "pones"),
    ("Ella ___ las plantas al sol.", "pone"),
    ("Ellos ___ salsa cubana.", "ponen"),
    ("Yo me ___ el traje de baño.", "pongo"),
    ("¿Dónde ___ yo las llaves?", "pongo"),
    ("Ustedes ___ la mesa.", "ponen"),
  ],
  "translate": [
    ("I put on music.", "Pongo música."),
    ("We set the table.", "Ponemos la mesa."),
    ("Will you turn on the A/C?", "¿Pones el aire?"),
    ("I put on sunscreen.", "Pongo crema solar."),
    ("She plays salsa.", "Ella pone salsa."),
    ("I put the keys on the table.", "Pongo las llaves en la mesa."),
  ],
  "speak": [
    "Say what music you put on with <span class='es'>pongo…</span>",
    "Describe setting the table: <span class='es'>pongo la mesa…</span>",
    "Say what you put on for the beach with <span class='es'>me pongo…</span>",
  ],
},
{
  "inf": "Salir",
  "meaning": "to leave / to go out",
  "gloss": "leaving, going out, dating",
  "when": [
    "Leaving: <span class='es'>Salgo de casa a las ocho.</span> — I leave home at eight.",
    "Going out: <span class='es'>Salimos a bailar.</span> — We go out dancing.",
    "Dating (salir con): <span class='es'>Salgo con mi novio.</span> — I'm dating my boyfriend.",
  ],
  "trick": "SALIR's yo takes the 'g' too: <strong>salgo</strong>. Picture yourself "
           "'sal-GO'-ing out the door. Rest is regular -ir.",
  "pattern": "Irregular yo (salgo); rest regular -ir.",
  "conj": _conj("salgo", "sales", "sale", "salimos", "salís", "salen"),
  "examples": [
    ("Salgo de casa a las siete para la playa.", "I leave home at seven for the beach."),
    ("Salimos a bailar salsa los viernes.", "We go out dancing salsa on Fridays."),
    ("Mi novio sale del trabajo a las cinco.", "My boyfriend leaves work at five."),
    ("¿A qué hora sales del gimnasio?", "What time do you leave the gym?"),
    ("Salgo con mi novio desde hace dos años.", "I've been dating my boyfriend for two years."),
    ("El sol sale temprano en verano.", "The sun rises early in summer."),
    ("Salimos a pasear con los perros.", "We go out to walk the dogs."),
    ("Ella sale a correr por la mañana.", "She goes out running in the morning."),
    ("Ellos salen a cenar los sábados.", "They go out to dinner on Saturdays."),
    ("Salgo temprano para evitar el tráfico.", "I leave early to avoid traffic."),
    ("¿Salimos esta noche?", "Shall we go out tonight?"),
    ("El barco sale del puerto.", "The boat leaves the port."),
  ],
  "fill": [
    ("Yo ___ de casa a las ocho.", "salgo"),
    ("Nosotros ___ a bailar.", "salimos"),
    ("¿Tú ___ del gimnasio?", "sales"),
    ("Mi novio ___ del trabajo.", "sale"),
    ("Ellos ___ a cenar.", "salen"),
    ("Yo ___ con mi novio.", "salgo"),
    ("El sol ___ temprano.", "sale"),
    ("¿Ustedes ___ esta noche?", "salen"),
  ],
  "translate": [
    ("I leave home at eight.", "Salgo de casa a las ocho."),
    ("We go out dancing.", "Salimos a bailar."),
    ("What time do you leave?", "¿A qué hora sales?"),
    ("I'm dating my boyfriend.", "Salgo con mi novio."),
    ("The sun rises early.", "El sol sale temprano."),
    ("Shall we go out tonight?", "¿Salimos esta noche?"),
  ],
  "speak": [
    "Say what time you leave the house with <span class='es'>salgo…</span>",
    "Describe a night out with <span class='es'>salimos a…</span>",
    "Say how long you've been dating with <span class='es'>salgo con… desde hace…</span>",
  ],
},
{
  "inf": "Oír",
  "meaning": "to hear",
  "gloss": "hearing sounds, music, someone talking",
  "when": [
    "Hearing sounds: <span class='es'>Oigo el mar.</span> — I hear the sea.",
    "\"Oye\" — the everyday \"hey / listen\": <span class='es'>Oye, ¿cómo estás?</span>",
    "vs. escuchar (to listen on purpose): oír just = the sound reaches you.",
  ],
  "trick": "OÍR is small but spiky: <strong>oigo</strong>, oyes, oye… A 'g' in yo and "
           "a 'y' in the middle forms. Remember Cubans say <span class='es'>¡Oye!</span> "
           "constantly — that's this verb.",
  "pattern": "Irregular yo (oigo) + spelling y in oyes/oye/oyen; accents on oír/oímos/oís.",
  "conj": _conj("oigo", "oyes", "oye", "oímos", "oís", "oyen"),
  "examples": [
    ("Oigo el mar desde la ventana.", "I hear the sea from the window."),
    ("Oye, ¿vamos a la playa?", "Hey, shall we go to the beach?"),
    ("No oigo bien con el ruido.", "I can't hear well with the noise."),
    ("Mi novio oye música cubana todo el día.", "My boyfriend hears Cuban music all day."),
    ("¿Oyes ese pájaro?", "Do you hear that bird?"),
    ("Oímos las olas por la noche.", "We hear the waves at night."),
    ("Los perros oyen todo.", "The dogs hear everything."),
    ("Oye, mi amor, ¿dónde estás?", "Hey, my love, where are you?"),
    ("No oigo el teléfono en el gimnasio.", "I can't hear the phone at the gym."),
    ("Ella oye el despertador a las seis.", "She hears the alarm at six."),
    ("¿Ustedes oyen la música desde ahí?", "Can you all hear the music from there?"),
    ("Oigo a los vecinos por la mañana.", "I hear the neighbors in the morning."),
  ],
  "fill": [
    ("Yo ___ el mar.", "oigo"),
    ("¿Tú ___ ese pájaro?", "oyes"),
    ("Nosotros ___ las olas.", "oímos"),
    ("Ella ___ el despertador.", "oye"),
    ("Los perros ___ todo.", "oyen"),
    ("Yo no ___ bien.", "oigo"),
    ("___, ¿cómo estás?", "Oye"),
    ("¿Ustedes ___ la música?", "oyen"),
  ],
  "translate": [
    ("I hear the sea.", "Oigo el mar."),
    ("Do you hear that bird?", "¿Oyes ese pájaro?"),
    ("We hear the waves.", "Oímos las olas."),
    ("Hey, how are you?", "Oye, ¿cómo estás?"),
    ("The dogs hear everything.", "Los perros oyen todo."),
    ("I can't hear well.", "No oigo bien."),
  ],
  "speak": [
    "Say three sounds you can hear now with <span class='es'>oigo…</span>",
    "Start a sentence with <span class='es'>Oye…</span> to get attention.",
    "Explain oír vs. escuchar in your own words.",
  ],
},
{
  "inf": "Querer",
  "meaning": "to want / to love",
  "gloss": "wanting things, wanting to do things, loving people",
  "when": [
    "Wanting a thing: <span class='es'>Quiero un café.</span> — I want a coffee.",
    "Wanting to do (querer + verb): <span class='es'>Quiero ir a la playa.</span>",
    "Loving people: <span class='es'>Te quiero.</span> — I love you.",
  ],
  "trick": "QUERER stem-changes e→ie (<strong>quiero</strong>) — the stressed 'e' "
           "'breaks' into 'ie'. And <span class='es'>te quiero</span> is how couples "
           "say 'I love you' day to day.",
  "pattern": "Stem change e→ie in all but nosotros/vosotros. Regular yo (quiero).",
  "conj": _conj("quiero", "quieres", "quiere", "queremos", "queréis", "quieren"),
  "examples": [
    ("Quiero un café cubano, por favor.", "I want a Cuban coffee, please."),
    ("Quiero ir a la playa hoy.", "I want to go to the beach today."),
    ("Te quiero mucho, mi amor.", "I love you a lot, my love."),
    ("Mi novio quiere cocinar esta noche.", "My boyfriend wants to cook tonight."),
    ("¿Quieres hacer paddleboard conmigo?", "Do you want to paddleboard with me?"),
    ("Queremos aprender a bailar salsa.", "We want to learn to dance salsa."),
    ("Los perros quieren salir al jardín.", "The dogs want to go out to the garden."),
    ("Quiero hablar español con tu familia.", "I want to speak Spanish with your family."),
    ("¿Qué quieres para la cena?", "What do you want for dinner?"),
    ("Ella quiere una casa cerca del mar.", "She wants a house near the sea."),
    ("Ellos quieren venir a la fiesta.", "They want to come to the party."),
    ("Quiero un jardín lleno de flores tropicales.", "I want a garden full of tropical flowers."),
  ],
  "fill": [
    ("Yo ___ un café.", "quiero"),
    ("¿Tú ___ ir a la playa?", "quieres"),
    ("Nosotros ___ aprender salsa.", "queremos"),
    ("Mi novio ___ cocinar.", "quiere"),
    ("Ellos ___ venir a la fiesta.", "quieren"),
    ("Yo te ___ mucho.", "quiero"),
    ("¿Qué ___ tú para la cena?", "quieres"),
    ("Los perros ___ salir.", "quieren"),
  ],
  "translate": [
    ("I want a coffee.", "Quiero un café."),
    ("Do you want to go to the beach?", "¿Quieres ir a la playa?"),
    ("I love you.", "Te quiero."),
    ("We want to learn salsa.", "Queremos aprender salsa."),
    ("He wants to cook.", "Él quiere cocinar."),
    ("What do you want for dinner?", "¿Qué quieres para la cena?"),
  ],
  "speak": [
    "List three things you want with <span class='es'>quiero…</span>",
    "Say three things you want to do with <span class='es'>quiero + verb</span>.",
    "Tell someone you love them: <span class='es'>te quiero</span>.",
  ],
},
{
  "inf": "Poder",
  "meaning": "can / to be able to",
  "gloss": "ability, possibility, permission",
  "when": [
    "Ability: <span class='es'>Puedo nadar bien.</span> — I can swim well.",
    "Asking permission/favors: <span class='es'>¿Puedo pagar con tarjeta?</span>",
    "Possibility: <span class='es'>Podemos ir mañana.</span> — We can go tomorrow.",
  ],
  "trick": "PODER stem-changes o→ue (<strong>puedo</strong>) — the 'o' 'breaks' into "
           "'ue'. Say it like \"PWAY-do.\" Always followed by another verb: "
           "<span class='es'>puedo + hacer</span>.",
  "pattern": "Stem change o→ue in all but nosotros/vosotros.",
  "conj": _conj("puedo", "puedes", "puede", "podemos", "podéis", "pueden"),
  "examples": [
    ("Puedo nadar muy bien.", "I can swim very well."),
    ("¿Puedes ayudarme con el español?", "Can you help me with Spanish?"),
    ("No podemos ir a la playa; hace viento.", "We can't go to the beach; it's windy."),
    ("Mi novio puede cocinar comida cubana.", "My boyfriend can cook Cuban food."),
    ("¿Puedo pagar con tarjeta?", "Can I pay with card?"),
    ("Puedo verte mañana en el café.", "I can see you tomorrow at the café."),
    ("Los perros pueden correr en la playa.", "The dogs can run on the beach."),
    ("¿Podemos hacer paddleboard hoy?", "Can we paddleboard today?"),
    ("No puedo dormir cuando hace calor.", "I can't sleep when it's hot."),
    ("Ella puede hablar tres idiomas.", "She can speak three languages."),
    ("¿Pueden ustedes venir el sábado?", "Can you all come on Saturday?"),
    ("Puedo entender un poco de español ahora.", "I can understand a little Spanish now."),
  ],
  "fill": [
    ("Yo ___ nadar.", "puedo"),
    ("¿Tú ___ ayudarme?", "puedes"),
    ("Nosotros no ___ ir hoy.", "podemos"),
    ("Mi novio ___ cocinar.", "puede"),
    ("Ellos ___ correr en la playa.", "pueden"),
    ("¿___ yo pagar con tarjeta?", "Puedo"),
    ("Ella ___ hablar tres idiomas.", "puede"),
    ("¿Ustedes ___ venir el sábado?", "pueden"),
  ],
  "translate": [
    ("I can swim.", "Puedo nadar."),
    ("Can you help me?", "¿Puedes ayudarme?"),
    ("We can't go today.", "No podemos ir hoy."),
    ("Can I pay with card?", "¿Puedo pagar con tarjeta?"),
    ("He can cook.", "Él puede cocinar."),
    ("Can you all come?", "¿Pueden venir?"),
  ],
  "speak": [
    "Say three things you can do with <span class='es'>puedo…</span>",
    "Ask three polite favors with <span class='es'>¿Puedes…?</span>",
    "Ask permission with <span class='es'>¿Puedo…?</span>",
  ],
},
{
  "inf": "Saber",
  "meaning": "to know (facts / how to do something)",
  "gloss": "knowing information or a skill",
  "when": [
    "Knowing facts: <span class='es'>Sé la respuesta.</span> — I know the answer.",
    "Knowing how (saber + verb): <span class='es'>Sé nadar.</span> — I know how to swim.",
    "vs. conocer — saber = information & skills, not people/places.",
  ],
  "trick": "SABER's yo is a lone accent: <strong>sé</strong> (\"I know\"). One little "
           "word. Use saber for facts and skills — 'I know HOW.'",
  "pattern": "Irregular yo (sé); rest regular -er.",
  "conj": _conj("sé", "sabes", "sabe", "sabemos", "sabéis", "saben"),
  "examples": [
    ("Sé nadar y hacer paddleboard.", "I know how to swim and paddleboard."),
    ("No sé cocinar comida cubana todavía.", "I don't know how to cook Cuban food yet."),
    ("¿Sabes dónde está el café?", "Do you know where the café is?"),
    ("Mi novio sabe bailar salsa muy bien.", "My boyfriend knows how to dance salsa very well."),
    ("Sabemos que hace calor en verano.", "We know it's hot in summer."),
    ("¿Sabes qué hora es?", "Do you know what time it is?"),
    ("No sé la respuesta.", "I don't know the answer."),
    ("Ella sabe hablar español e inglés.", "She knows how to speak Spanish and English."),
    ("Los perros saben cuándo es la hora de comer.", "The dogs know when it's mealtime."),
    ("¿Saben ustedes la dirección?", "Do you all know the address?"),
    ("Sé un poco de español, pero quiero aprender más.", "I know a little Spanish, but I want to learn more."),
    ("No sabemos si va a llover.", "We don't know if it's going to rain."),
  ],
  "fill": [
    ("Yo ___ nadar.", "sé"),
    ("¿Tú ___ dónde está el café?", "sabes"),
    ("Nosotros ___ que hace calor.", "sabemos"),
    ("Mi novio ___ bailar salsa.", "sabe"),
    ("Ellos ___ la dirección.", "saben"),
    ("Yo no ___ la respuesta.", "sé"),
    ("¿___ tú qué hora es?", "Sabes"),
    ("Ustedes ___ hablar español.", "saben"),
  ],
  "translate": [
    ("I know how to swim.", "Sé nadar."),
    ("Do you know where the café is?", "¿Sabes dónde está el café?"),
    ("We know it's hot.", "Sabemos que hace calor."),
    ("He knows how to dance.", "Él sabe bailar."),
    ("I don't know the answer.", "No sé la respuesta."),
    ("Do you know what time it is?", "¿Sabes qué hora es?"),
  ],
  "speak": [
    "Say three skills you have with <span class='es'>sé + verb</span>.",
    "Say three facts you know with <span class='es'>sé que…</span>",
    "Ask someone if they know something with <span class='es'>¿Sabes…?</span>",
  ],
},
{
  "inf": "Conocer",
  "meaning": "to know (people / places) / to meet",
  "gloss": "being familiar with people, places, things",
  "when": [
    "Knowing people: <span class='es'>Conozco a tu familia.</span> — I know your family.",
    "Knowing places: <span class='es'>Conozco Miami bien.</span> — I know Miami well.",
    "Meeting for the first time: <span class='es'>Quiero conocer Cuba.</span>",
  ],
  "trick": "CONOCER's yo gets a 'z': <strong>conozco</strong> (\"co-NOTH-co\"). Use it "
           "for people & places you're <em>familiar</em> with — you can't 'know a fact' "
           "with conocer, only be acquainted.",
  "pattern": "Irregular yo (conozco, c→zc); rest regular -er.",
  "conj": _conj("conozco", "conoces", "conoce", "conocemos", "conocéis", "conocen"),
  "examples": [
    ("Conozco a tu familia cubana.", "I know your Cuban family."),
    ("Conozco Miami muy bien.", "I know Miami very well."),
    ("¿Conoces un buen restaurante cubano?", "Do you know a good Cuban restaurant?"),
    ("Mi novio conoce a todos en el barrio.", "My boyfriend knows everyone in the neighborhood."),
    ("Quiero conocer La Habana algún día.", "I want to get to know Havana someday."),
    ("Conocemos una playa tranquila cerca de aquí.", "We know a quiet beach near here."),
    ("No conozco a esa persona.", "I don't know that person."),
    ("Ella conoce muchas plantas tropicales.", "She knows many tropical plants."),
    ("Los perros conocen el camino a la playa.", "The dogs know the way to the beach."),
    ("¿Conocen ustedes a mi novio?", "Do you all know my boyfriend?"),
    ("Conozco esta canción; es de Cuba.", "I know this song; it's from Cuba."),
    ("Quiero conocer a tus amigos.", "I want to meet your friends."),
  ],
  "fill": [
    ("Yo ___ a tu familia.", "conozco"),
    ("¿Tú ___ un buen restaurante?", "conoces"),
    ("Nosotros ___ una playa tranquila.", "conocemos"),
    ("Mi novio ___ a todos.", "conoce"),
    ("Ellos ___ el camino.", "conocen"),
    ("Yo ___ Miami muy bien.", "conozco"),
    ("Ella ___ muchas plantas.", "conoce"),
    ("¿Ustedes ___ a mi novio?", "conocen"),
  ],
  "translate": [
    ("I know your family.", "Conozco a tu familia."),
    ("Do you know a good restaurant?", "¿Conoces un buen restaurante?"),
    ("We know a quiet beach.", "Conocemos una playa tranquila."),
    ("He knows everyone.", "Él conoce a todos."),
    ("I want to get to know Havana.", "Quiero conocer La Habana."),
    ("I don't know that person.", "No conozco a esa persona."),
  ],
  "speak": [
    "Say three people or places you know with <span class='es'>conozco…</span>",
    "Say a place you want to get to know with <span class='es'>quiero conocer…</span>",
    "Ask if someone knows a good spot with <span class='es'>¿Conoces…?</span>",
  ],
},
]

# quick lookup by infinitive
BY_INF = {v["inf"]: v for v in VERBS}
