# -*- coding: utf-8 -*-
"""Data + conjugators for the VERB WORKBOOK — a dedicated companion to the
Hablar workbook that teaches the Spanish *verb system*:

  • Present tense as a system (regular families + the four irregular patterns)
  • Ser vs estar, reflexives, gustar, present progressive
  • A gentle on-ramp into the PAST (preterite + imperfect)
  • A gentle on-ramp into the FUTURE (ir a + infinitive, and the future tense)

Regular forms are generated by small conjugators so they're guaranteed
consistent; irregular forms are hand-coded and checked. Every example is
personalized to Celeste's real life: Florida, the beach, paddleboarding, her
dog, the garden, the gym, music, cooking, café cubano, work, texting, and her
Cuban boyfriend.
"""

PRONOUNS = ["yo", "tú", "él / ella / usted", "nosotros",
            "vosotros", "ellos / ellas / ustedes"]

# short pronoun labels for compact reference tables
PRON_SHORT = ["yo", "tú", "él/ella/ud.", "nosotros", "vosotros", "ellos/uds."]


def _zip(forms):
    return list(zip(PRONOUNS, forms))


# ══════════════════════════════════════════════════════════════════════════
# REGULAR CONJUGATORS  — the reliable machinery
# ══════════════════════════════════════════════════════════════════════════
_PRESENT = {
    "ar": ["o", "as", "a", "amos", "áis", "an"],
    "er": ["o", "es", "e", "emos", "éis", "en"],
    "ir": ["o", "es", "e", "imos", "ís", "en"],
}
_PRETERITE = {
    "ar": ["é", "aste", "ó", "amos", "asteis", "aron"],
    "er": ["í", "iste", "ió", "imos", "isteis", "ieron"],
    "ir": ["í", "iste", "ió", "imos", "isteis", "ieron"],
}
_IMPERFECT = {
    "ar": ["aba", "abas", "aba", "ábamos", "abais", "aban"],
    "er": ["ía", "ías", "ía", "íamos", "íais", "ían"],
    "ir": ["ía", "ías", "ía", "íamos", "íais", "ían"],
}
_FUTURE = ["é", "ás", "á", "emos", "éis", "án"]  # added to the whole infinitive


def stem(inf):
    return inf[:-2]


def ending(inf):
    return inf[-2:]


def present(inf):
    return [stem(inf) + e for e in _PRESENT[ending(inf)]]


def preterite(inf):
    return [stem(inf) + e for e in _PRETERITE[ending(inf)]]


def imperfect(inf):
    return [stem(inf) + e for e in _IMPERFECT[ending(inf)]]


def future(inf):
    return [inf + e for e in _FUTURE]


def conj(inf, tense):
    return _zip({"present": present, "preterite": preterite,
                 "imperfect": imperfect, "future": future}[tense](inf))


# ══════════════════════════════════════════════════════════════════════════
# PART 1 — REGULAR MODEL VERBS  (one per family, taught in full)
# ══════════════════════════════════════════════════════════════════════════
REGULAR_MODELS = [
    {
        "inf": "hablar", "en": "to speak / to talk", "fam": "-ar",
        "note": "The model for every regular -ar verb — the biggest family by far.",
        "examples": [
            ("Hablo español con mi novio todos los días.", "I speak Spanish with my boyfriend every day."),
            ("¿Hablas inglés en el trabajo?", "Do you speak English at work?"),
            ("Ella habla muy rápido, como los cubanos.", "She speaks very fast, like Cubans do."),
            ("Hablamos por teléfono cada noche.", "We talk on the phone every night."),
            ("Ellos hablan de música en la playa.", "They talk about music at the beach."),
        ],
    },
    {
        "inf": "comer", "en": "to eat", "fam": "-er",
        "note": "The model for regular -er verbs. Notice the endings use 'e'.",
        "examples": [
            ("Como fruta antes de ir al gimnasio.", "I eat fruit before going to the gym."),
            ("¿Comes carne o eres vegetariana?", "Do you eat meat or are you vegetarian?"),
            ("Mi perro come demasiado rápido.", "My dog eats too fast."),
            ("Comemos arroz con pollo los domingos.", "We eat rice with chicken on Sundays."),
            ("Ellos comen en la playa después de nadar.", "They eat at the beach after swimming."),
        ],
    },
    {
        "inf": "vivir", "en": "to live", "fam": "-ir",
        "note": "The model for regular -ir verbs. Endings match -er except nosotros/vosotros.",
        "examples": [
            ("Vivo en Florida, cerca del mar.", "I live in Florida, near the sea."),
            ("¿Dónde vives tú?", "Where do you live?"),
            ("Mi novio vive a diez minutos de la playa.", "My boyfriend lives ten minutes from the beach."),
            ("Vivimos rodeados de plantas tropicales.", "We live surrounded by tropical plants."),
            ("Ellos viven la vida con alegría.", "They live life with joy."),
        ],
    },
]

# A generous bank of regular verbs Celeste will actually use (for reference +
# practice). (infinitive, english, family)
REGULAR_BANK = [
    ("caminar", "to walk", "-ar"), ("nadar", "to swim", "-ar"),
    ("cocinar", "to cook", "-ar"), ("trabajar", "to work", "-ar"),
    ("estudiar", "to study", "-ar"), ("escuchar", "to listen (to)", "-ar"),
    ("cantar", "to sing", "-ar"), ("bailar", "to dance", "-ar"),
    ("descansar", "to rest", "-ar"), ("tomar", "to take / to drink", "-ar"),
    ("mirar", "to look at / to watch", "-ar"), ("llevar", "to carry / to wear", "-ar"),
    ("comprar", "to buy", "-ar"), ("usar", "to use", "-ar"),
    ("regar", "to water (plants)", "-ar"), ("pasear", "to walk (the dog) / stroll", "-ar"),
    ("beber", "to drink", "-er"), ("aprender", "to learn", "-er"),
    ("leer", "to read", "-er"), ("correr", "to run", "-er"),
    ("comprender", "to understand", "-er"), ("vender", "to sell", "-er"),
    ("responder", "to answer", "-er"), ("romper", "to break", "-er"),
    ("escribir", "to write", "-ir"), ("abrir", "to open", "-ir"),
    ("recibir", "to receive", "-ir"), ("subir", "to go up / to upload", "-ir"),
    ("compartir", "to share", "-ir"), ("decidir", "to decide", "-ir"),
]


# ══════════════════════════════════════════════════════════════════════════
# PART 2 — THE FOUR IRREGULAR PATTERNS  (expanded from the PDF)
# ══════════════════════════════════════════════════════════════════════════
# Each irregular verb: inf, en, present forms (6), pattern key, a memory hook,
# and personalized examples.

def V(inf, en, forms, pattern, hook, examples):
    return {"inf": inf, "en": en, "conj": _zip(forms),
            "forms": forms, "pattern": pattern, "hook": hook,
            "examples": examples}


# --- Pattern A: only the YO form is irregular (the "-go" and "-zco" verbs) ---
YO_IRREGULAR = [
    V("hacer", "to do / to make", ["hago", "haces", "hace", "hacemos", "hacéis", "hacen"],
      "yo-go", "Everything is regular except <b>hago</b> — the yo form grows a 'g'.",
      [("Hago ejercicio en la playa por la mañana.", "I do exercise at the beach in the morning."),
       ("¿Qué haces este fin de semana?", "What are you doing this weekend?"),
       ("Ella hace café cubano muy fuerte.", "She makes very strong Cuban coffee.")]),
    V("poner", "to put / to set", ["pongo", "pones", "pone", "ponemos", "ponéis", "ponen"],
      "yo-go", "Only <b>pongo</b> is irregular — I 'plug in' a g.",
      [("Pongo música cuando cocino.", "I put on music when I cook."),
       ("Pongo la tabla de remo en el carro.", "I put the paddleboard in the car."),
       ("¿Dónde pones las llaves?", "Where do you put the keys?")]),
    V("salir", "to leave / to go out", ["salgo", "sales", "sale", "salimos", "salís", "salen"],
      "yo-go", "Only <b>salgo</b> grows the g.",
      [("Salgo a correr al amanecer.", "I go out to run at dawn."),
       ("Salgo con mi novio el sábado.", "I'm going out with my boyfriend on Saturday."),
       ("El sol sale a las seis y media.", "The sun comes up at six thirty.")]),
    V("traer", "to bring", ["traigo", "traes", "trae", "traemos", "traéis", "traen"],
      "yo-go", "Yo form adds <b>-igo</b>: <b>traigo</b>.",
      [("Traigo agua y fruta a la playa.", "I bring water and fruit to the beach."),
       ("¿Traes tu perro al parque?", "Do you bring your dog to the park?"),
       ("Él siempre trae buena energía.", "He always brings good energy.")]),
    V("conocer", "to know (people/places)", ["conozco", "conoces", "conoce", "conocemos", "conocéis", "conocen"],
      "yo-zco", "Yo form becomes <b>-zco</b>: <b>conozco</b>. (Verbs ending in -cer/-cir do this.)",
      [("Conozco un café cubano increíble.", "I know an amazing Cuban café."),
       ("¿Conoces La Habana?", "Do you know / Have you been to Havana?"),
       ("Ella conoce a toda la familia de él.", "She knows his whole family.")]),
    V("ver", "to see / to watch", ["veo", "ves", "ve", "vemos", "veis", "ven"],
      "yo-eo", "Slightly odd yo form: <b>veo</b> (keeps the e).",
      [("Veo delfines desde la tabla de remo.", "I see dolphins from the paddleboard."),
       ("¿Ves esa planta? Necesita agua.", "Do you see that plant? It needs water."),
       ("Vemos películas en español para practicar.", "We watch movies in Spanish to practice.")]),
    V("dar", "to give", ["doy", "das", "da", "damos", "dais", "dan"],
      "yo-oy", "Yo form ends in <b>-oy</b>: <b>doy</b> (like voy, soy, estoy).",
      [("Doy un paseo con el perro cada tarde.", "I take a walk with the dog every afternoon."),
       ("Te doy un beso.", "I give you a kiss."),
       ("Ellos dan clases de salsa.", "They give salsa classes.")]),
    V("saber", "to know (facts/how to)", ["sé", "sabes", "sabe", "sabemos", "sabéis", "saben"],
      "yo-odd", "Only the yo form is odd: <b>sé</b> (with an accent, to look different from 'se').",
      [("Sé nadar muy bien.", "I know how to swim very well."),
       ("¿Sabes la dirección del gimnasio?", "Do you know the address of the gym?"),
       ("Ella sabe cocinar comida cubana.", "She knows how to cook Cuban food.")]),
]

# --- Pattern B: STEM-CHANGING (boot) verbs — change in every form but nosotros/vosotros
STEM_CHANGING = {
    "e→ie": [
        V("querer", "to want / to love", ["quiero", "quieres", "quiere", "queremos", "queréis", "quieren"],
          "e→ie", "e becomes ie inside the boot.",
          [("Quiero aprender más verbos hoy.", "I want to learn more verbs today."),
           ("Te quiero mucho.", "I love you a lot."),
           ("¿Quieres ir a la playa?", "Do you want to go to the beach?")]),
        V("pensar", "to think", ["pienso", "piensas", "piensa", "pensamos", "pensáis", "piensan"],
          "e→ie", "Piensa in the boot; pensamos stays flat.",
          [("Pienso en ti todo el día.", "I think about you all day."),
           ("¿Qué piensas de la clase?", "What do you think of the class?"),
           ("Nosotros pensamos igual.", "We think the same.")]),
        V("empezar", "to begin", ["empiezo", "empiezas", "empieza", "empezamos", "empezáis", "empiezan"],
          "e→ie", "Empiezo… but empezamos.",
          [("Empiezo el día con café cubano.", "I start the day with Cuban coffee."),
           ("La clase de yoga empieza a las siete.", "The yoga class begins at seven."),
           ("Empezamos a cocinar juntos.", "We're starting to cook together.")]),
        V("preferir", "to prefer", ["prefiero", "prefieres", "prefiere", "preferimos", "preferís", "prefieren"],
          "e→ie", "Prefiero la playa; preferimos stays flat.",
          [("Prefiero nadar por la mañana.", "I prefer to swim in the morning."),
           ("¿Prefieres té o café?", "Do you prefer tea or coffee?"),
           ("Ella prefiere la música en vivo.", "She prefers live music.")]),
        V("entender", "to understand", ["entiendo", "entiendes", "entiende", "entendemos", "entendéis", "entienden"],
          "e→ie", "Entiendo… but entendemos.",
          [("No entiendo esta palabra.", "I don't understand this word."),
           ("¿Entiendes a los cubanos cuando hablan rápido?", "Do you understand Cubans when they talk fast?"),
           ("Ahora entiendo el patrón.", "Now I understand the pattern.")]),
    ],
    "o→ue": [
        V("poder", "to be able / can", ["puedo", "puedes", "puede", "podemos", "podéis", "pueden"],
          "o→ue", "o becomes ue inside the boot.",
          [("Puedo verte esta noche.", "I can see you tonight."),
           ("¿Puedes ayudarme con el jardín?", "Can you help me with the garden?"),
           ("No podemos ir hoy, hay tormenta.", "We can't go today, there's a storm.")]),
        V("dormir", "to sleep", ["duermo", "duermes", "duerme", "dormimos", "dormís", "duermen"],
          "o→ue", "Duermo… but dormimos.",
          [("Duermo con la ventana abierta.", "I sleep with the window open."),
           ("El perro duerme en mi cama.", "The dog sleeps in my bed."),
           ("Dormimos ocho horas.", "We sleep eight hours.")]),
        V("volver", "to return / come back", ["vuelvo", "vuelves", "vuelve", "volvemos", "volvéis", "vuelven"],
          "o→ue", "Vuelvo… but volvemos.",
          [("Vuelvo del gimnasio a las nueve.", "I get back from the gym at nine."),
           ("¿A qué hora vuelves?", "What time do you come back?"),
           ("Volvemos a la playa mañana.", "We're going back to the beach tomorrow.")]),
        V("contar", "to count / to tell", ["cuento", "cuentas", "cuenta", "contamos", "contáis", "cuentan"],
          "o→ue", "Cuento… but contamos.",
          [("Te cuento un secreto.", "I'll tell you a secret."),
           ("Cuento hasta diez en español.", "I count to ten in Spanish."),
           ("Ella cuenta historias de Cuba.", "She tells stories about Cuba.")]),
        V("encontrar", "to find", ["encuentro", "encuentras", "encuentra", "encontramos", "encontráis", "encuentran"],
          "o→ue", "Encuentro… but encontramos.",
          [("No encuentro mis llaves.", "I can't find my keys."),
           ("¿Encuentras conchas en la playa?", "Do you find shells at the beach?"),
           ("Encontramos un restaurante nuevo.", "We found a new restaurant.")]),
    ],
    "e→i": [
        V("pedir", "to ask for / to order", ["pido", "pides", "pide", "pedimos", "pedís", "piden"],
          "e→i", "e becomes i (only in -ir verbs).",
          [("Pido un café con leche.", "I order a coffee with milk."),
           ("¿Qué pides normalmente?", "What do you usually order?"),
           ("Pedimos la cuenta, por favor.", "We ask for the check, please.")]),
        V("servir", "to serve / to be useful", ["sirvo", "sirves", "sirve", "servimos", "servís", "sirven"],
          "e→i", "Sirvo… but servimos.",
          [("Sirvo la comida a las ocho.", "I serve dinner at eight."),
           ("Este cuaderno me sirve para practicar.", "This notebook is useful for practicing."),
           ("El café no sirve frío.", "Coffee is no good cold.")]),
        V("repetir", "to repeat", ["repito", "repites", "repite", "repetimos", "repetís", "repiten"],
          "e→i", "Repito… but repetimos.",
          [("Repito cada frase en voz alta.", "I repeat each sentence out loud."),
           ("¿Puedes repetir, por favor?", "Can you repeat, please?"),
           ("Repetimos el verbo hasta memorizarlo.", "We repeat the verb until we memorize it.")]),
    ],
    "u→ue": [
        V("jugar", "to play (a sport/game)", ["juego", "juegas", "juega", "jugamos", "jugáis", "juegan"],
          "u→ue", "The only common u→ue verb: juego.",
          [("Juego con el perro en el jardín.", "I play with the dog in the yard."),
           ("¿Juegas al voleibol de playa?", "Do you play beach volleyball?"),
           ("Jugamos cartas cuando llueve.", "We play cards when it rains.")]),
    ],
}

# --- Pattern C: COMPLETELY IRREGULAR — memorize as songs ---
FULLY_IRREGULAR = [
    V("ser", "to be (permanent: who/what)", ["soy", "eres", "es", "somos", "sois", "son"],
      "irregular", "Sing it: soy-eres-es, somos-sois-son.",
      [("Soy de Florida.", "I'm from Florida."),
       ("Mi novio es cubano.", "My boyfriend is Cuban."),
       ("Somos una pareja feliz.", "We are a happy couple.")]),
    V("estar", "to be (temporary: state/place)", ["estoy", "estás", "está", "estamos", "estáis", "están"],
      "irregular", "Note the accents: estás, está, están.",
      [("Estoy en la playa ahora mismo.", "I'm at the beach right now."),
       ("¿Cómo estás?", "How are you?"),
       ("El café está caliente.", "The coffee is hot.")]),
    V("ir", "to go", ["voy", "vas", "va", "vamos", "vais", "van"],
      "irregular", "Tiny and irregular: voy-vas-va, vamos-vais-van.",
      [("Voy al gimnasio a las seis.", "I go to the gym at six."),
       ("¿Vas a la playa hoy?", "Are you going to the beach today?"),
       ("Vamos a bailar salsa.", "We're going to dance salsa.")]),
    V("haber", "there is / there are (hay)", ["he", "has", "ha", "hemos", "habéis", "han"],
      "irregular", "You'll mostly meet its special form <b>hay</b> = 'there is/are'. The full set builds past-perfect later.",
      [("Hay mucha gente en la playa hoy.", "There are a lot of people at the beach today."),
       ("Hay café recién hecho.", "There's fresh coffee."),
       ("¿Hay tormenta esta tarde?", "Is there a storm this afternoon?")]),
]

# --- Pattern D: COMBINATION — irregular yo form + a stem change ---
COMBINATION = [
    V("tener", "to have", ["tengo", "tienes", "tiene", "tenemos", "tenéis", "tienen"],
      "combo", "Irregular yo (<b>tengo</b>) + e→ie stem change (<b>tienes</b>).",
      [("Tengo un perro cariñoso.", "I have an affectionate dog."),
       ("¿Cuántos años tienes?", "How old are you? (lit. how many years do you have?)"),
       ("Tenemos ganas de viajar a Cuba.", "We feel like traveling to Cuba.")]),
    V("venir", "to come", ["vengo", "vienes", "viene", "venimos", "venís", "vienen"],
      "combo", "Irregular yo (<b>vengo</b>) + e→ie (<b>vienes</b>).",
      [("Vengo de la playa, estoy cansada.", "I'm coming from the beach, I'm tired."),
       ("¿Vienes a cenar esta noche?", "Are you coming to dinner tonight?"),
       ("Mi novio viene de Cuba.", "My boyfriend comes from Cuba.")]),
    V("decir", "to say / to tell", ["digo", "dices", "dice", "decimos", "decís", "dicen"],
      "combo", "Irregular yo (<b>digo</b>) + e→i (<b>dices</b>).",
      [("Siempre digo la verdad.", "I always tell the truth."),
       ("¿Qué dices?", "What are you saying?"),
       ("Ella dice 'asere' como los cubanos.", "She says 'asere' like Cubans do.")]),
    V("oír", "to hear", ["oigo", "oyes", "oye", "oímos", "oís", "oyen"],
      "combo", "Irregular yo (<b>oigo</b>) + a y appears (<b>oyes</b>).",
      [("Oigo las olas desde la casa.", "I hear the waves from the house."),
       ("¿Oyes esa canción?", "Do you hear that song?"),
       ("No te oigo bien, hay mucho viento.", "I can't hear you well, it's very windy.")]),
]


# ══════════════════════════════════════════════════════════════════════════
# SER vs ESTAR  (both mean "to be")
# ══════════════════════════════════════════════════════════════════════════
SER_USES = [
    ("Identity — who/what something is", "Soy Celeste. Él es mi novio.", "I'm Celeste. He's my boyfriend."),
    ("Origin — where you're from", "Soy de Florida. Él es de Cuba.", "I'm from Florida. He's from Cuba."),
    ("Permanent traits", "El café cubano es dulce.", "Cuban coffee is sweet."),
    ("Profession", "Soy instructora de yoga.", "I'm a yoga instructor."),
    ("Time & dates", "Son las ocho. Hoy es martes.", "It's eight o'clock. Today is Tuesday."),
    ("What something's made of", "La tabla es de fibra de vidrio.", "The board is made of fiberglass."),
]
ESTAR_USES = [
    ("Location — where something is", "Estoy en la playa. El perro está en casa.", "I'm at the beach. The dog is home."),
    ("Feelings & moods", "Estoy feliz hoy.", "I'm happy today."),
    ("Temporary states", "El agua está fría.", "The water is cold (right now)."),
    ("Health", "Estoy cansada después del gimnasio.", "I'm tired after the gym."),
    ("-ando / -iendo (in progress)", "Estoy cocinando.", "I'm cooking."),
    ("Result of a change", "La puerta está abierta.", "The door is open."),
]
SER_ESTAR_CONTRAST = [
    ("Él es aburrido.", "He is boring (personality).", "Él está aburrido.", "He is bored (right now)."),
    ("Ella es guapa.", "She is good-looking (always).", "Ella está guapa hoy.", "She looks great today."),
    ("El café es rico.", "Coffee is delicious (in general).", "El café está rico.", "This coffee tastes great."),
    ("Estoy lista.", "— (with estar) I'm ready.", "Soy lista.", "I'm clever/smart."),
]


# ══════════════════════════════════════════════════════════════════════════
# REFLEXIVE VERBS  (daily routine — extremely useful)
# ══════════════════════════════════════════════════════════════════════════
REFLEX_PRONOUNS = ["me", "te", "se", "nos", "os", "se"]
REFLEXIVE = [
    ("levantarse", "to get up", ["me levanto", "te levantas", "se levanta", "nos levantamos", "os levantáis", "se levantan"],
     "Me levanto temprano para ver el amanecer.", "I get up early to watch the sunrise."),
    ("despertarse", "to wake up (e→ie)", ["me despierto", "te despiertas", "se despierta", "nos despertamos", "os despertáis", "se despiertan"],
     "Me despierto a las seis con el sol.", "I wake up at six with the sun."),
    ("ducharse", "to shower", ["me ducho", "te duchas", "se ducha", "nos duchamos", "os ducháis", "se duchan"],
     "Me ducho después de la playa.", "I shower after the beach."),
    ("vestirse", "to get dressed (e→i)", ["me visto", "te vistes", "se viste", "nos vestimos", "os vestís", "se visten"],
     "Me visto con ropa cómoda para el gimnasio.", "I get dressed in comfy clothes for the gym."),
    ("acostarse", "to go to bed (o→ue)", ["me acuesto", "te acuestas", "se acuesta", "nos acostamos", "os acostáis", "se acuestan"],
     "Me acuesto tarde cuando hablo con mi novio.", "I go to bed late when I talk with my boyfriend."),
    ("llamarse", "to be called / named", ["me llamo", "te llamas", "se llama", "nos llamamos", "os llamáis", "se llaman"],
     "Me llamo Celeste. ¿Cómo te llamas?", "My name is Celeste. What's your name?"),
    ("sentirse", "to feel (e→ie)", ["me siento", "te sientes", "se siente", "nos sentimos", "os sentís", "se sienten"],
     "Me siento fuerte después de nadar.", "I feel strong after swimming."),
]


# ══════════════════════════════════════════════════════════════════════════
# GUSTAR AND FRIENDS  (backwards verbs)
# ══════════════════════════════════════════════════════════════════════════
GUSTAR_PRON = [("me", "to me"), ("te", "to you"), ("le", "to him/her/you-formal"),
               ("nos", "to us"), ("os", "to you-all (Spain)"), ("les", "to them/you-all")]
GUSTAR_LIKE = [
    ("gustar", "to like (lit. to be pleasing)", "Me gusta la playa. Me gustan los perros.",
     "I like the beach. I like dogs."),
    ("encantar", "to love (things)", "Me encanta el café cubano.", "I love Cuban coffee."),
    ("doler", "to hurt", "Me duelen los pies después de correr.", "My feet hurt after running."),
    ("faltar", "to be lacking / to need", "Me falta practicar más.", "I need to practice more."),
    ("importar", "to matter", "No me importa la lluvia.", "The rain doesn't matter to me."),
    ("interesar", "to be interesting to", "Me interesa la cultura cubana.", "Cuban culture interests me."),
]


# ══════════════════════════════════════════════════════════════════════════
# PRESENT PROGRESSIVE  (estar + -ando/-iendo)  — "right now"
# ══════════════════════════════════════════════════════════════════════════
GERUNDS = [
    ("hablar", "hablando", "regular -ar → -ando"),
    ("comer", "comiendo", "regular -er → -iendo"),
    ("escribir", "escribiendo", "regular -ir → -iendo"),
    ("leer", "leyendo", "vowel + -iendo → -yendo"),
    ("oír", "oyendo", "→ -yendo"),
    ("dormir", "durmiendo", "-ir stem change o→u"),
    ("pedir", "pidiendo", "-ir stem change e→i"),
    ("decir", "diciendo", "-ir stem change e→i"),
    ("venir", "viniendo", "-ir stem change e→i"),
]
PROG_EXAMPLES = [
    ("Estoy nadando en el mar.", "I am swimming in the sea."),
    ("Estás hablando muy rápido.", "You are talking very fast."),
    ("Ella está cocinando arroz con frijoles.", "She is cooking rice and beans."),
    ("Estamos escuchando música cubana.", "We are listening to Cuban music."),
    ("El perro está durmiendo en el sofá.", "The dog is sleeping on the couch."),
]


# ══════════════════════════════════════════════════════════════════════════
# STEPPING INTO THE PAST  (preterite + imperfect)
# ══════════════════════════════════════════════════════════════════════════
PRET_REGULAR_MODELS = [
    ("hablar", "-ar", ["hablé", "hablaste", "habló", "hablamos", "hablasteis", "hablaron"]),
    ("comer", "-er", ["comí", "comiste", "comió", "comimos", "comisteis", "comieron"]),
    ("vivir", "-ir", ["viví", "viviste", "vivió", "vivimos", "vivisteis", "vivieron"]),
]
PRET_IRREGULAR = [
    ("ser / ir", "was/went (identical!)", ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"]),
    ("hacer", "did/made", ["hice", "hiciste", "hizo", "hicimos", "hicisteis", "hicieron"]),
    ("tener", "had", ["tuve", "tuviste", "tuvo", "tuvimos", "tuvisteis", "tuvieron"]),
    ("estar", "was (state/place)", ["estuve", "estuviste", "estuvo", "estuvimos", "estuvisteis", "estuvieron"]),
    ("decir", "said", ["dije", "dijiste", "dijo", "dijimos", "dijisteis", "dijeron"]),
    ("dar", "gave", ["di", "diste", "dio", "dimos", "disteis", "dieron"]),
]
PRET_EXAMPLES = [
    ("Ayer nadé una hora en el mar.", "Yesterday I swam for an hour in the sea."),
    ("Anoche cociné arroz con pollo.", "Last night I cooked rice with chicken."),
    ("Fui a la playa el sábado.", "I went to the beach on Saturday."),
    ("Mi novio hizo café cubano esta mañana.", "My boyfriend made Cuban coffee this morning."),
    ("Tuvimos un día perfecto.", "We had a perfect day."),
]

IMPERF_REGULAR_MODELS = [
    ("hablar", "-ar", ["hablaba", "hablabas", "hablaba", "hablábamos", "hablabais", "hablaban"]),
    ("comer", "-er", ["comía", "comías", "comía", "comíamos", "comíais", "comían"]),
    ("vivir", "-ir", ["vivía", "vivías", "vivía", "vivíamos", "vivíais", "vivían"]),
]
IMPERF_IRREGULAR = [
    ("ser", "used to be / was", ["era", "eras", "era", "éramos", "erais", "eran"]),
    ("ir", "used to go / was going", ["iba", "ibas", "iba", "íbamos", "ibais", "iban"]),
    ("ver", "used to see / was seeing", ["veía", "veías", "veía", "veíamos", "veíais", "veían"]),
]
IMPERF_EXAMPLES = [
    ("Cuando era niña, vivía cerca del mar.", "When I was a girl, I lived near the sea."),
    ("Todos los veranos íbamos a la playa.", "Every summer we used to go to the beach."),
    ("Mi abuela cocinaba comida cubana los domingos.", "My grandmother used to cook Cuban food on Sundays."),
    ("Antes no hablaba nada de español.", "Before, I didn't speak any Spanish."),
    ("El cielo estaba gris y llovía.", "The sky was grey and it was raining."),
]

# Preterite vs imperfect — the decision guide
PRET_VS_IMPERF = [
    ("A single, completed action", "PRETERITE", "Ayer fui a la playa.", "Yesterday I went to the beach."),
    ("What happened next (a sequence)", "PRETERITE", "Llegué, nadé y comí.", "I arrived, swam, and ate."),
    ("A sudden interruption", "PRETERITE", "Sonó el teléfono.", "The phone rang."),
    ("Used-to / habitual in the past", "IMPERFECT", "De niña nadaba cada día.", "As a girl I used to swim every day."),
    ("Background, weather, time, age", "IMPERFECT", "Eran las ocho y hacía calor.", "It was eight o'clock and it was hot."),
    ("An ongoing action (was …-ing)", "IMPERFECT", "Yo cocinaba cuando llamó.", "I was cooking when he called."),
]


# ══════════════════════════════════════════════════════════════════════════
# STEPPING INTO THE FUTURE  (ir a + infinitive, and the future tense)
# ══════════════════════════════════════════════════════════════════════════
IR_A_EXAMPLES = [
    ("Voy a nadar esta tarde.", "I'm going to swim this afternoon."),
    ("¿Vas a venir a la playa?", "Are you going to come to the beach?"),
    ("Vamos a cocinar juntos esta noche.", "We're going to cook together tonight."),
    ("Mi novio va a visitar a su familia.", "My boyfriend is going to visit his family."),
    ("Va a llover mañana.", "It's going to rain tomorrow."),
]
FUT_REGULAR_MODEL = [
    ("hablar", ["hablaré", "hablarás", "hablará", "hablaremos", "hablaréis", "hablarán"]),
    ("comer", ["comeré", "comerás", "comerá", "comeremos", "comeréis", "comerán"]),
    ("vivir", ["viviré", "vivirás", "vivirá", "viviremos", "viviréis", "vivirán"]),
]
FUT_IRREGULAR_STEMS = [
    ("tener", "tendr-", "tendré"), ("venir", "vendr-", "vendré"),
    ("poner", "pondr-", "pondré"), ("salir", "saldr-", "saldré"),
    ("poder", "podr-", "podré"), ("saber", "sabr-", "sabré"),
    ("hacer", "har-", "haré"), ("decir", "dir-", "diré"),
    ("querer", "querr-", "querré"), ("haber", "habr-", "habrá (hay → there will be)"),
]
FUT_EXAMPLES = [
    ("Algún día hablaré español con fluidez.", "Someday I'll speak Spanish fluently."),
    ("El año que viene iré a Cuba.", "Next year I'll go to Cuba."),
    ("Tendremos una casa cerca del mar.", "We'll have a house near the sea."),
    ("¿Qué harás este verano?", "What will you do this summer?"),
    ("Mañana hará sol.", "Tomorrow it will be sunny."),
]


# ══════════════════════════════════════════════════════════════════════════
# ONE VERB ACROSS TIME  (the timeline — same verb, three tenses)
# ══════════════════════════════════════════════════════════════════════════
TIMELINE = [
    ("nadar", "Ayer nadé.", "I swam.", "Hoy nado.", "I swim / I'm swimming.",
     "Mañana voy a nadar / nadaré.", "I'm going to swim / I will swim."),
    ("comer", "Anoche comí.", "I ate.", "Ahora como.", "I eat / I'm eating.",
     "Luego voy a comer / comeré.", "I'm going to eat / I will eat."),
    ("ir", "Fui a la playa.", "I went to the beach.", "Voy a la playa.", "I go to the beach.",
     "Voy a ir / iré a la playa.", "I'm going to go / I'll go to the beach."),
    ("hacer", "Hice café.", "I made coffee.", "Hago café.", "I make coffee.",
     "Voy a hacer / haré café.", "I'm going to make / I'll make coffee."),
]
